include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Enforce a maximum of 80 characters per line for readability.
    lines_longer_than_80_chars: false

    # Ensures trailing commas are used in multiline function calls and collections.
    require_trailing_commas: true

    # Enforces putting required parameters first in constructors for clarity.
    always_put_required_named_parameters_first: true

    # Encourages using final for variables that are not reassigned.
    prefer_final_locals: true

    # Requires using const constructors when possible.
    prefer_const_constructors: true

    # Ensures const keyword is used where possible for optimization.
    prefer_const_declarations: true

    # Ensures only lowercase letters and underscores are used in file names.
    file_names: true

    # Prevents using empty else blocks to keep the code clean.
    empty_statements: false

    # Enforces correct casing for constant identifiers.
    constant_identifier_names: true

    # Requires private fields that are not accessed outside the file to be final.
    prefer_final_fields: true

    # Avoids single character variable names, except for indices in loops.
    avoid_single_cascade_in_expression_statements: true

    # Encourages using single quotes for consistency in string literals.
    prefer_single_quotes: true

    # Enforces the use of unawaited in async methods to highlight unhandled futures.
    unawaited_futures: true

    # Prevents printing logs directly; encourages using a logging package.
    avoid_print: true

    # Ensures nullable fields have appropriate null safety in function parameters.
    avoid_positional_boolean_parameters: true

    # Avoids using magic numbers in code by encouraging named constants instead.
    avoid_redundant_argument_values: true


# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
