name: weather
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.1+2

environment:
  sdk: ^3.5.3
  flutter: 3.24.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.2.2
  flutter_bloc: ^8.1.6
  equatable: ^2.0.7
  gap: ^3.0.1
  fpdart: ^1.1.1
  logger: ^2.4.0
  get_it: ^8.0.3
  shimmer_animation: ^2.2.1
  cached_network_image: ^3.4.1
  geolocator: ^12.0.0
  permission_handler: ^10.0.0
  sqflite: ^2.4.1
  path_provider: ^2.1.0
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  # fonts
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Regular.ttf
